[project]
name = "upscaler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.139.2",
    "matplotlib>=3.11.0",
    "mlflow>=3",
    "numpy>=2.5.1",
    "pillow>=12.3.0",
    "pyqt5>=5.15.11",
    "python-multipart>=0.0.32",
    "torch>=2.13.0",
    "uvicorn[standard]>=0.51.0",
]
